# Generated by Django 3.1.3 on 2021-01-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_auto_20210118_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='liked',
        ),
        migrations.AddField(
            model_name='comment',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
